### ISSUE TITLE
Spider: Southwestern Pennsylvania Commission

### ISSUE THREAD

**Issue by maxachis** [pgh-public-meetings/city-scrapers-pitt#107]
## Spider Name: 
Southwestern Pennsylvania Commission

## Website: 
https://www.spcregion.org/

**Comment by maxachis** [comment]
I'm on this!

**Comment by vnbcs** [comment]
@maxachis u should put the name of the agency in the heading!

**Comment by vnbcs** [comment]
@maxachis how DARE u name this issue incorrectly. u are a DISGRACE

**Comment by bonfirefan** [comment]
<___< 
>___>

**Comment by vnbcs** [comment]
@maxachis jk ur lovely 🌼

**Comment by maxachis** [comment]
I don't know whether to feel flattered or disturbed. 

So I'll feel both! :D
