### ISSUE TITLE
Spider: Pittsburgh Task Force on Public Algorithms

### ISSUE THREAD

**Issue by vnbcs** [pgh-public-meetings/city-scrapers-pitt#113]
## Spider Name: 
pitt_public_algorithms_task_force

## Website: 
https://www.cyber.pitt.edu/community-meetings

## Scraping Notes:
make sure to include the RSVP links!

**Comment by ben-nathanson** [comment]
Public meetings are "Postponed" due to the public health issue.

**Comment by woodyeagle** [comment]
I will work on this.  This will be my first one on here.

**Comment by woodyeagle** [comment]
Spider merged in.

**Comment by ben-nathanson** [comment]
Closed by #141
