### ISSUE TITLE
Allegheny County Council Scraper Not Working And Pandemic Changes

### ISSUE THREAD

**Issue by maxachis** [pgh-public-meetings/city-scrapers-pitt#119]
The [Allegheny County Council web scraper ](https://github.com/pgh-public-meetings/city-scrapers-pitt/blob/master/city_scrapers/spiders/alle_county.py)is currently not working, and changes have been made to the format of meetings, as described below

Council President Patrick Catena announced on Marhc 18th that he is “strongly encouraging Members to call-in and is discouraging the public from attending in person but rather watch the live-stream and to submit public comment online.”

The capacity of the meeting room will be limited to 10, in accordance with federal guidelines on social distances, according to a county press release.

Comment can be submitted via email at CntyCouncil@AlleghenyCounty.US or via the online sign-up form at https://apps.alleghenycounty.us/website/CouncilReqComm.asp.

The meeting livestream can be accessed at http://allegheny.granicus.com/ViewPublisher.php?view_id=4.

**Comment by maxachis** [comment]
Link to Allegheny Council Meeting Videos

http://allegheny.granicus.com/ViewPublisher.php?view_id=4.

**Comment by maxachis** [comment]
These issues appear to be related to the failed build and AWS authentication issues, and not with the code within the spider itself.

**Comment by ben-nathanson** [comment]
Thanks for creating this issue @maxachis. After verifying that 1) the spider runs successfully locally and 2) events for county council show up on the production website where they should be. Granted the AWS issues may have been fixed outside of this issue.
