### ISSUE TITLE
Spider: Jail Oversight Board

### ISSUE THREAD

**Issue by dkori** [pgh-public-meetings/city-scrapers-pitt#126]
## Spider Name: 
alle_jail

## Website: 
https://alleghenycontroller.com/jailoversight/

## Scraping Notes:
HTML page, meetings are either virtual or located at 436 Grant Street,

**Comment by woodyeagle** [comment]
I'll work on this one.

**Comment by bonfirefan** [comment]
@woodyeagle are you still working on this?

**Comment by woodyeagle** [comment]
Yes.  Getting close to finishing it.
