### ISSUE TITLE
city_scrapers_core module note found error

### ISSUE THREAD

**Issue by bonfirefan** [pgh-public-meetings/city-scrapers-pitt#127]
`ModuleNotFoundError: no module named 'city_scrapers_core'`

Is a common issue. the solution is to uninstall then re-install `city_scrapers_core` with 

```
pipenv uninstall city_scrapers_core
pipenv install city_scrapers_core
```

**Comment by maxachis** [comment]
It *may* also have something to do with the version of python you are running. I am not 100% certain, but I updated to the latest version of python (3.8.3), and after doing that and reopen my shell and pipenv, it functioned. Again, not entirely sure if that is the solution, but it was the only thing I did after running the "uninstall city_scrapers_core" and "install city_scrapers_core" commands (although restarting the shell might have also contributed).
