### ISSUE TITLE
[Sentry] pitt_city_planning  AttributeError("'NoneType' object has no attribute 'group'")

### ISSUE THREAD

**Issue by bonfirefan** [pgh-public-meetings/city-scrapers-pitt#168]
`[pitt_city_planning] AttributeError("'NoneType' object has no attribute 'group'")`
 Looks like the original URL is now out of date: 

- Old link: https://pittsburghpa.gov/dcp/notice
- New link: https://pittsburghpa.gov/dcp/virtual-pc (this is the virtual planning commission link)

We should probably add a new spider for the Virtual Zoning Board of Adjustments: https://pittsburghpa.gov/dcp/virtual-zba

**Comment by ben-nathanson** [comment]
Thanks for spotting this! I'll look into making new spider(s) for planning and zoning. I will probably name them something like `pitt_city_planning_planning_comission` and `pitt_city_planning_zoning_board`.
