### ISSUE TITLE
[Sentry] [pa_development] website changed

### ISSUE THREAD

**Issue by bonfirefan** [pgh-public-meetings/city-scrapers-pitt#173]
Error: `[pa_development] JSONDecodeError('Expecting value: line 3 column 1 (char 4)')`
It looks like the URL used is no longer valid: https://dced.pa.gov/wp-json/tribe/events/v1/events
Worth digging for the new JSON source

**Comment by ben-nathanson** [comment]
Weird! This appears to conform to the [Wordpress Events Calendar Rest API](https://theeventscalendar.com/knowledgebase/k/introduction-to-the-events-calendar-rest-api/), and "https://dced.pa.gov/wp-json/tribe/events/v1/events" does return a `200`, but the content of the entire page is literally `'\r\n\r\n'`. Whereas it used to be a giant JSON blob that we could parse into events. 

Another wrinkle in things is that _I can't find the new meetings page publicly_. Not clear what the path forward here is until we can find if/where new meetings are being posted.

**Comment by ben-nathanson** [comment]
Events still show up (here)[https://dced.pa.gov/events/2020-10/?tribe-bar-date=2020-10&tribe-bar-search=PEDFA]. Perhaps the raw events JSON is only available internally now? Assuming the server is now populating the calendar before sending it to the client.

**Comment by ben-nathanson** [comment]
It seems like there's a JSON blob for a single month being embedded within the [page](view-source:https://dced.pa.gov/events/), which may confirm my idea that the server is grabbing a subset of the data and passing it on. Basically this should be a small (if annoying) fix on our end. Still hopeful I won't have to scrape one month at a time.

**Comment by bonfirefan** [comment]
@mishugana pointed out that the old link appears to be working. It's possible that it breaks occasionally, but seems to be up so I will close this issue.
