### ISSUE TITLE
Spider: Allegheny County Finance and Development Commission

### ISSUE THREAD

**Issue by pjsier** [pgh-public-meetings/city-scrapers-pitt#18]
## Spider Name: 
`alle_finance_dev`

## Website: 
http://www.county.allegheny.pa.us/economic-development/authorities/meetings-reports/fdc/meetings.aspx

## Scraping Notes:
Currently, the Finance and Development Commission (FDC) meetings include the meetings for all of the following organizations:

Higher Education Building Authority (HEBA)
Hospital Development Authority (HDA)
Industrial Development Authority (IDA)
Residential Finance Authority (RFA)

**Comment by reesemcardle** [comment]
I'm working on this

**Comment by reesemcardle** [comment]
**Bad SSL on www.county.allegheny.pa.us domain**

(http://www.county.allegheny.pa.us/economic-development/authorities/meetings-reports/fdc/meetings.aspx)

**Use** 

https://alleghenycounty.us/economic-development/authorities/meetings-reports/fdc/meetings.aspx

**Comment by YujiShen** [comment]
I will work on this one.

**Comment by bonfirefan** [comment]
Thanks @YujiShen ! Let us know if you have any issues!

**Comment by ben-nathanson** [comment]
Closed by #101
