### ISSUE TITLE
Spider: Allegheny County Board of Health

### ISSUE THREAD

**Issue by dataneer** [pgh-public-meetings/city-scrapers-pitt#27]
## Spider Name:
alle_health

## Website: 
https://www.alleghenycounty.us/Health-Department/Resources/About/Board-of-Health/Public-Meeting-Schedule.aspx

## Scraping Notes:
N/A

**Comment by cityscrapers-brian** [comment]
let's see what I can do with this.

**Comment by cityscrapers-brian** [comment]
Okay, working on this.

**Comment by cityscrapers-brian2** [comment]
I have a working scraper.  Let's see if I can figure out this git stuff.

**Comment by henryCraig** [comment]
Hey how is this scraper coming along?

**Comment by cityscrapers-brian2** [comment]
It's written and working ... there's a pull request in Github ( https://github.com/bonfirefan/city-scrapers-pitt/pull/58 ) ... but I'm still figuring out this infrastructure stuff of Git and code style/format enforcement.

**Comment by maxachis** [comment]
Just doing some spring cleaning -- the pull request for this was accepted a while ago, so I think it's safe to close this issue.
