### ISSUE TITLE
Spider: Pittsburgh Post-Gazette Online

### ISSUE THREAD

**Issue by bonfirefan** [pgh-public-meetings/city-scrapers-pitt#32]
## Spider Name: 
pitt_news_gazette

## Website: 
http://classmart.post-gazette.com/pa/legal-notices/search

## Scraping Notes:
This spider will need to categorize events from multiple different agencies and likely use some regular expressions

**Comment by synapticarbors** [comment]
I'll take a crack at this one.

**Comment by synapticarbors** [comment]
Actually looking at the webpage more carefully, I am not 100% what useful information is on there and the original impetus for wanting to scrape this page. If someone can provide an example of the type of information that is wanted, I'm happy to re-visit it.

**Comment by henryCraig** [comment]
I'm going to start working on this.

**Comment by bonfirefan** [comment]
Redundant issue - see Issue #182
