### ISSUE TITLE
Another site: Allegheny Alerts

### ISSUE THREAD

**Issue by cityscrapers-brian** [pgh-public-meetings/city-scrapers-pitt#56]
Appears to be run by the Allegheny County government.
https://member.everbridge.net/index/453003085611110

**Comment by cityscrapers-brian** [comment]
Okay -- after a little investigation, my impression:

there's no event info that you can read via WWW, but if you give them an email address (or other contact method) they'll send you "alerts".

We could set up a program to be the recipient of these alerts--not sure if there'd be anything we'd care about.

**Comment by ben-nathanson** [comment]
I subscribed to the service. If I find anything that might be relevant, I will report back so we can decide whether to pursue this further.

**Comment by maxachis** [comment]
@ben-nathanson -- Have we heard anything further from this?

**Comment by ben-nathanson** [comment]
Here's a sampling of what I got:
![image](https://user-images.githubusercontent.com/24640705/99890600-fe35f980-2c2e-11eb-8c33-c8e9c7096f73.png)
I'm going to close this issue unless others have strong feelings - the kind of content I'm finding in these emails is too unstructured to be practical for automation. These are more like press releases than consistent meeting descriptions.
