### ISSUE TITLE
Spider: Pittsburgh Ethics Hearing Board

### ISSUE THREAD

**Issue by pjsier** [pgh-public-meetings/city-scrapers-pitt#6]
## Spider Name: 
`pitt_ethics_board`

## Website: 
http://pittsburghpa.gov/ehb/ehb-meetings

**Comment by MartinSeibert** [comment]
I'm working on this one

**Comment by vnbcs** [comment]
I'm trying to work on this

**Comment by ben-nathanson** [comment]
resolved by #99
