### ISSUE TITLE
Spider: Housing Authority of the City of Pittsburgh

### ISSUE THREAD

**Issue by pjsier** [pgh-public-meetings/city-scrapers-pitt#7]
## Spider Name: 
`pitt_housing`

## Website: 
https://hacp.org

**Comment by thatKennedy** [comment]
okay going to try to get this backup and running leveraging this previous work: https://github.com/City-Bureau/city-scrapers/pull/579

**Comment by ben-nathanson** [comment]
Looks like their website went through a redesign sometime after April of 2019.

[Now](http://www.hacp.org/)
[April 2019](https://web.archive.org/web/20181130133533/http://www.hacp.org/)

We might still be able to parse[this](https://hacp.org/hacp-board-of-commissioners-meeting/) page for meetings.

**Comment by dkori** [comment]
Working on it but can pass the code to someone else who really wants to work on it (being used as a demo)

**Comment by wsnavely** [comment]
I might look at this tonight!

**Comment by maxachis** [comment]
This spider has been successfully added to the github, so this issue is closed!

![Alt Text](https://steamuserimages-a.akamaihd.net/ugc/921427206947773938/E2F15721B22F1743B257B9FC33647146BC157E30/)
